// actionTypes.js

export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';
export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';
export const GET_USERS_REQUEST = 'auth/GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'auth/GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'auth/GET_USERS_FAILURE';
export const GET_USER_BY_ID_REQUEST = 'auth/GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'auth/GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'auth/GET_USER_BY_ID_FAILURE';
export const GET_USER_BY_NAME_REQUEST = 'auth/GET_USER_BY_NAME_REQUEST';
export const GET_USER_BY_NAME_SUCCESS = 'auth/GET_USER_BY_NAME_SUCCESS';
export const GET_USER_BY_NAME_FAILURE = 'auth/GET_USER_BY_NAME_FAILURE';
export const GET_CURRENT_USER_REQUEST = 'auth/GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'auth/GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'auth/GET_CURRENT_USER_FAILURE';


export const ADD_BOOK_REQUEST = 'book/ADD_BOOK_REQUEST';
export const ADD_BOOK_SUCCESS = 'book/ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'book/ADD_BOOK_FAILURE';
export const GET_BOOK_REQUEST = 'book/GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'book/GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'book/GET_BOOK_FAILURE';
export const GET_BOOK_BY_ID_REQUEST = 'book/GET_BOOK_BY_ID_REQUEST';
export const GET_BOOK_BY_ID_SUCCESS = 'book/GET_BOOK_BY_ID_SUCCESS';
export const GET_BOOK_BY_ID_FAILURE = 'book/GET_BOOK_BY_ID_FAILURE';
export const GET_BOOK_BY_NAME_REQUEST = 'book/GET_BOOK_BY_NAME_REQUEST';
export const GET_BOOK_BY_NAME_SUCCESS = 'book/GET_BOOK_BY_NAME_SUCCESS';
export const GET_BOOK_BY_NAME_FAILURE = 'book/GET_BOOK_BY_NAME_FAILURE';
export const GET_CURRENT_BOOK_REQUEST = 'book/GET_CURRENT_BOOK_REQUEST';
export const GET_CURRENT_BOOK_SUCCESS = 'book/GET_CURRENT_BOOK_SUCCESS';
export const GET_CURRENT_BOOK_FAILURE = 'book/GET_CURRENT_BOOK_FAILURE';
export const DELETE_BOOK_REQUEST = 'book/DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'book/DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'book/DELETE_BOOK_FAILURE';